server:
  port: 8081

# 数据库
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/aidevicemanager?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:com/deepblue/census/*/mapper/*.xml

